platform :ios, '8.0'

use_frameworks!

target 'KZ_EnlargeImage_iOS' do
    
    pod 'KZ_FPSLabel'
    pod 'KZ_WebImage'
    pod 'KZ_ReuseScrollView'
    pod 'KZ_Categories'
    pod 'KZ_MacroDefinition'

end
